config/routes.rb
Rails.application.routes.draw do
  root :to => "events#show", id: 5

  get "1" => "events#show", id: 1
  get "2" => "events#show", id: 2
  get "3" => "events#show", id: 3
  get "4" => "events#show", id: 4
  get "5" => "events#show", id: 5
  get "uxeye" => "events#show", id: 4
  get "history" => "histories#index"
  get "history/1" => "histories#show", id: 1
  get "history/2" => "histories#show", id: 2
  get "history/3" => "histories#show", id: 3
  get "history/4" => "histories#show", id: 4

  namespace :admin do
    root :to => "events#index"
    get "/" => "events#index"

    get "logout" => "sessions#destroy", as: "logout"
    get "login" => "sessions#new", as: "login"
    post "login" => "sessions#create"

    get 'stat' => "stats#index", :as => "stat"
    get 'stat_query' => "stats#query", :as => "stat_query"

    match "oauth/callback" => "oauth#callback", :via => :all
    match "oauth/:provider" => "oauth#oauth", :as => :auth_at_provider, :via => :all

    resources :events do
      resources :rooms
      resources :periods do
        resources :programs do
          resources :speakers
        end
      end
      resources :organizer_groups do
        resources :organizers
      end
      resources :organizers
      resources :supporters
    end
    resources :users
  end
end

app/models/organizer.rb
# == Schema Information
#
# Table name: organizers
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  name_en            :string(255)
#  photo              :string(255)
#  link               :string(255)
#  position           :integer
#  event_id           :integer
#  organizer_group_id :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class Organizer < ActiveRecord::Base
  mount_uploader :photo, ProfileUploader

  belongs_to :organizer_group
  belongs_to :event
	
  validates :event_id, presence: true
  
  scope :free_organizers, -> { where(organizer_group_id: nil) }
  
end

app/controllers/admin/organizers_controller.rb
class Admin::OrganizersController < ApplicationController
	before_filter :require_organizer
	layout 'admin'
	
  def new
    @organizer = Organizer.new
  end
  def create
    params[:organizer][:event_id] = params[:event_id]
    params[:organizer][:organizer_group_id] = params[:organizer_group_id] || nil
    @organizer = Organizer.new(organizer_params)
    if @organizer.save
      redirect_to admin_event_path(params[:event_id]), notice: '오거나이저를 추가했습니다.'
    else
			p @organizer.errors
      render action: 'new'
    end
  end

  def edit
    @organizer = Organizer.find(params[:id])
  end
  def update
    @organizer = Organizer.find(params[:id])
    if @organizer.update(organizer_params)
      redirect_to admin_event_path(params[:event_id]), notice: '오거나이저를 수정했습니다.'
    else
			p @organizer.errors
      render action: 'edit'
    end
  end
  
  def index
    redirect_to admin_event_path(params[:event_id])
  end

  def destroy
    @organizer = Organizer.find(params[:id])
    @organizer.destroy
		redirect_to admin_event_path(params[:event_id]), notice: '오거나이저를 삭제했습니다.'
  end

  private
  def organizer_params
    params.require(:organizer).permit(:name, :name_en, :event_id, :link, :organizer_group_id, :photo, :position)
  end
end

app/views/admin/organizers/_form.html.erb
<% url = params[:action] == "new" ? admin_event_organizers_path : admin_event_organizer_path %>

<div class="w300">
	<%= simple_form_for [:admin, @organizer], url: url do |f| %>
		<%= hidden_field_tag :organizer_group_id, params[:organizer_group_id] if params[:action] == "new" %>
		<% @errors = @organizer.errors.messages %>

		<%= f.input :photo, label: "프로필 사진", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:photo) %>
		<br>
		<%= f.input :name, label: "이름", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:name) %>
		<br>
		<%= f.input :name_en, label: "영문 이름", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:name_en) %>
		<br>
		<%= f.input :link, label: "링크", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:link) %>
		<br>
		<% unless params[:action] == "new" %>
			<%= f.input :organizer_group_id, collection: Event.find(params[:event_id]).organizer_groups, label: "그룹", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
			<% flash_error_message(:role) %>
			<br>
		<% end %>
		<%= f.input :position, label: "순서", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:position) %>
		<br>
		<% if params[:action] == "edit" %>
			<%= link_to '오거나이저 삭제', admin_event_organizer_path(@organizer.event, @organizer), method: :delete, data: { confirm: "잘못 누른게 아니라면 삭제합니다."}, class: "btn btn-danger w100p tac" %>
		<% end %>
		<hr>
		<%= render "/admin/events/form_confirm_or_cancel" %>
	<% end %>
</div>

app/views/admin/organizers/edit.html.erb
<h1>오거나이저 수정</h1>

<%= render 'form' %>

app/views/admin/organizers/new.html.erb
<h1>새 오거나이저 추가</h1>

<%= render 'form' %>