config/routes.rb
Rails.application.routes.draw do
  root :to => "events#show", id: 5

  get "1" => "events#show", id: 1
  get "2" => "events#show", id: 2
  get "3" => "events#show", id: 3
  get "4" => "events#show", id: 4
  get "5" => "events#show", id: 5
  get "uxeye" => "events#show", id: 4
  get "history" => "histories#index"
  get "history/1" => "histories#show", id: 1
  get "history/2" => "histories#show", id: 2
  get "history/3" => "histories#show", id: 3
  get "history/4" => "histories#show", id: 4

  namespace :admin do
    root :to => "events#index"
    get "/" => "events#index"

    get "logout" => "sessions#destroy", as: "logout"
    get "login" => "sessions#new", as: "login"
    post "login" => "sessions#create"

    get 'stat' => "stats#index", :as => "stat"
    get 'stat_query' => "stats#query", :as => "stat_query"

    match "oauth/callback" => "oauth#callback", :via => :all
    match "oauth/:provider" => "oauth#oauth", :as => :auth_at_provider, :via => :all

    resources :events do
      resources :rooms
      resources :periods do
        resources :programs do
          resources :speakers
        end
      end
      resources :organizer_groups do
        resources :organizers
      end
      resources :organizers
      resources :supporters
    end
    resources :users
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  poster     :string(255)
#  starts_at  :date
#  ends_at    :date
#  view_count :integer          default(0)
#  position   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Event < ActiveRecord::Base
  mount_uploader :poster, PosterUploader

  has_many :rooms, :dependent => :destroy
  has_many :periods, :dependent => :destroy
  has_many :organizer_groups, :dependent => :destroy
  has_many :organizers, :dependent => :destroy
  has_many :supporters, :dependent => :destroy
    
	validates :title, presence: true
  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
	before_filter :require_organizer
	layout 'admin'
	
  def index
    @events = Event.all.order("id desc")
  end

  def show
    @event = Event.find(params[:id])
    @periods = @event.periods.order("starts_at")
    @organizergroups = @event.organizer_groups.order("position")
    @organizers = @event.organizers.order("position")
    @supporters = @event.supporters.order("position")
  end

  def new
    @event = Event.new
  end
  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_events_path, notice: '행사가 만들어졌습니다.'
    else
			p @event.errors
      render action: 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end
  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to admin_event_path(@event), notice: '행사가 수정되었습니다.'
    else
			p @event.errors
      render action: 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
		redirect_to admin_events_path, notice: '행사가 삭제되었습니다.'
  end

  private
  def event_params
    params.require(:event).permit(:title, :summary, :position, :starts_at, :ends_at, :poster)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'camp5th'

  def show
    @event = Event.find(params[:id])
    @periods = @event.periods.order("starts_at")
    @organizergroups = @event.organizer_groups.order("position")
    @organizers = @event.organizers.order("position")
    @supporters = @event.supporters.order("position")
    @event.increment!(:view_count)
  end

end

app/views/admin/events/_form.html.erb
<div class="w300">
	<%= simple_form_for [:admin, @event] do |f| %>
		<% @errors = @event.errors.messages %>

		<%= f.input :title, label: "행사 제목", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:title) %>
		<br>
		<%= f.input :summary, label: "행사 개요", label_html: { class: "fwb" }, input_html: { class: "form-control", rows: 10 }, error: false %>
		<% flash_error_message(:summary) %>
		<br>
		<%= f.input :poster, label: "행사 포스터", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:poster) %>
		<br>
		<%= f.label :starts_at, "행사 시작일" %>
		<input type="text" id="event_starts_at" name="event[starts_at]" class="w150 string form-control" value="<%= 8.days.ago.to_date %>">
		<% flash_error_message(:starts_at) %>
		<br>
		<%= f.label :ends_at, "행사 종료일" %>
		<input type="text" id="event_ends_at" name="event[ends_at]" class="w150 string form-control" value="<%= Date.yesterday %>">
		<% flash_error_message(:ends_at) %>
		<script>
		$(function() {
		    $( "#event_starts_at" ).datepicker({
					dateFormat: "yy-mm-dd",
		      defaultDate: "-1w -1d",
		      changeMonth: true,
		      onClose: function( selectedDate ) {
		        $( "#event_starts_at" ).datepicker( "option", selectedDate );
		      }
		    });
		    $( "#event_ends_at" ).datepicker({
					dateFormat: "yy-mm-dd",
			    defaultDate: "-1",
		      changeMonth: true,
		      onClose: function( selectedDate ) {
		        $( "#event_ends_at" ).datepicker( "option", selectedDate );
		      }
		    });
		  });
		</script>
		<br>
		<%= f.input :position, label: "정렬 순서", label_html: { class: "fwb" }, input_html: { class: "w75 form-control" }, error: false %>
		<% flash_error_message(:position) %>
		<hr>
		<%= render "/shared/form_confirm_or_cancel" %>
	<% end %>
</div>

app/views/admin/events/_form_confirm_or_cancel.html.erb
<%= button_tag type: "submit", class: "btn btn-success fr" do %>
	<span class="glyphicon glyphicon-ok"></span> 확인
<% end %>
<%= link_to '취소', admin_event_path(params[:event_id]), class: "btn btn-default fl" %>

app/views/admin/events/_information.html.erb
<div class="information_section section">
	<div class="poster"><%= image_tag(@event.poster.url(:w240)) if @event.poster.present? %></div>
	<div class="info">
		<div class="fl w100p">
			<h2 class="fl"><%= @event.title %></h2>
			<% if current_user.admin? %>
				<div class="btn-group fr">
					<%= link_to '행사 수정', edit_admin_event_path(@event), class: "btn btn-warning" %>
					<%= link_to '행사 삭제', admin_event_path(@event), method: :delete, data: { confirm: "잘못 누른게 아니라면 삭제합니다. 이 작업은 위험합니다."}, class: "btn btn-danger" %>
				</div>
			<% else %>
				<div class="btn-group fr">
					<%= link_to '행사 수정', "/", class: "btn btn-warning disabled" %>
					<%= link_to '행사 삭제', "/", class: "btn btn-danger disabled" %>
				</div>
			<% end %>				
		</div>
		<br>
		<p class="summary"><%= @event.summary.html_safe if @event.summary.present? %></p>
		행사 기간 : 
		<% if hdate(@event.starts_at, "") == hdate(@event.ends_at, "") %>
			<%= hdate(@event.starts_at, "") %> 하루
		<% else %>
			<%= hdate(@event.starts_at, "") %> ~ <%= hdate(@event.ends_at, "") %>
		<% end %>
		<br>
		사용하는 방 수 : <%= @event.rooms.count %><br>
		조회수 : <%= @event.view_count %><br>
		정렬 순서 : <%= @event.position.present? ? @event.position : "따로 지정되지 않음" %><br>
	</div>
</div>

app/views/admin/events/_organizer.html.erb
<div class="organizers_section section">
	<h3>오거나이저</h3>
	<% if @organizergroups.blank? %>
		<p class="w100p tac">오거나이저가 아무도 없습니다.</p>
		<div class="new_organizer_group">
			<%= link_to new_admin_event_organizer_group_path(@event) do %>
				<div class="new_photo btn btn-success"><span class="fcw fwn glyphicon glyphicon-plus fs10"></span> 오거나이저 그룹 추가</div>
			<% end %>
				
	<% else %>
		<div class="organizers">
			<% @organizergroups.each do |group| %>
				<h4 class="di w100p fl"><%= group.name %><%= link_to "", edit_admin_event_organizer_group_path(@event, group), class: "fs10 glyphicon glyphicon-cog orange" %><%= link_to "", admin_event_organizer_group_path(@event, group), method: :delete, data: { confirm: "잘못 누른게 아니라면 삭제합니다."}, class: "fs10 glyphicon glyphicon-remove fcr" %></h4>
				<ul class="group">
					<% group.organizers.each do |organizer| %>
						<li class="organizer">
							<%= link_to edit_admin_event_organizer_group_organizer_path(@event, group, organizer) do %>
								<div class="photo"><%= image_tag(organizer.photo.url(:w80)) if organizer.photo.present? %></div>
							<% end %>
							<% if organizer.link.present? %>
								<%= link_to organizer.name, "http://" + organizer.link.gsub("http://", "").gsub("https://", ""), target: "_blank" %>
							<% else %>
								<%= organizer.name %>
							<% end %>
						</li>
					<% end %>
					<li class="new_organizer">
						<%= link_to new_admin_event_organizer_group_organizer_path(@event, group) do %>
							<div class="new_photo btn btn-success">+</div>
							추가 
						<% end %>
					</li>
				</ul>
			<% end %>
			<% if @event.organizers.free_organizers.count > 0 %>
				<h4 class="di w100p fl">미지정</h4>
				<ul class="group">
					<% @event.organizers.free_organizers.each do |organizer| %>
						<li class="organizer">
							<%= link_to edit_admin_event_organizer_path(@event, organizer) do %>
								<div class="photo"><%= image_tag(organizer.photo.url(:w80)) if organizer.photo.present? %></div>
							<% end %>
							<% if organizer.link.present? %>
								<%= link_to organizer.name, organizer.link %>
							<% else %>
								<%= organizer.name %>
							<% end %>
						</li>
					<% end %>
				</ul>
			<% end %>
			<div class="new_organizer_group">
				<%= link_to new_admin_event_organizer_group_path(@event) do %>
					<div class="new_photo btn btn-success"><span class="fcw fwn glyphicon glyphicon-plus fs10"></span> 오거나이저 그룹 추가</div> 
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/admin/events/_program.html.erb
<div class="programs_section section">
	<h3>프로그램</h3>
	<% room_cnt = "room#{@event.rooms.count}" %>
	<table class="programs table table-bordered table-striped <%= room_cnt %>">
		<thead>
			<tr class="rooms">
				<td>
					<%= link_to "방 추가", new_admin_event_room_path(@event), class: "btn btn-success btn-xs m10 w80" %>
				</td>
				<% @event.rooms.each do |room| %>
					<td>
						<h4><%= room.name %></h4>
						<%= link_to "", edit_admin_event_room_path(@event, room), class: "fs10 glyphicon glyphicon-cog orange" %>
						<%= link_to "", admin_event_room_path(@event, room), method: :delete, data: { confirm: "잘못 누른게 아니라면 삭제합니다."}, class: "fs10 glyphicon glyphicon-remove fcr" %>
					</td>
				<% end %>
			</tr>
		</thead>
		<tbody>
		<% @periods.each do |period| %>
			<tr>
				<td class="time">
					<h4><%= htime(period.starts_at) %><br>~<br><%= htime(period.ends_at) %></h4>
						<%= link_to "", edit_admin_event_period_path(@event, period), class: "fs10 glyphicon glyphicon-cog orange" %>
						<%= link_to "", admin_event_period_path(@event, period), method: :delete, data: { confirm: "잘못 누른게 아니라면 삭제합니다."}, class: "fs10 glyphicon glyphicon-remove fcr" %>
						<%= link_to "프로그램 추가", new_admin_event_period_program_path(@event, period), class: "btn btn-success btn-xs mt5 mb10 w80" %>
				</td>
				<% if period.programs.blank? %>
					<td colspan="<%= @event.rooms.count %>"></td>
				<% else %>
					<% period.programs.each do |program| %>
					<td class="session" colspan="<%= @event.rooms.count if program.room_id.blank? %>">
						<div class="title">
							<h4 class="di"><%= program.title %></h4><%= "<span class='room'> (#{program.room.name})</span>".html_safe if program.room_id.present? %>
							<%= link_to "", edit_admin_event_period_program_path(@event, period, program), class: "fs10 glyphicon glyphicon-cog orange" %>
							<%= link_to "", admin_event_period_program_path(@event, period, program), method: :delete, data: { confirm: "잘못 누른게 아니라면 삭제합니다."}, class: "fs10 glyphicon glyphicon-remove fcr" %>
						</div>
						<p class="content <%= 'nil' unless program.content.present? %>"><%= truncate(program.content, length: 60) %></p>
						<div class="speakers">
							<% program.speakers.each do |speaker| %>
								<div class="btn-group btn-group-xs speaker mr0 mb5">
									<% if speaker.link.present? %>
										<%= link_to speaker.name, speaker.link, class: "btn btn-default" %>
									<% else %>
										<button class="btn btn-default" disabled=disabled><%= speaker.name %></button>
									<% end %>
									<%= link_to(edit_admin_event_period_program_speaker_path(@event, period, program, speaker), class: "btn btn-warning") do %>
										<span class="fcw fwn glyphicon glyphicon-cog fs10"></span>
									<% end %>
									<%= link_to(admin_event_period_program_speaker_path(@event, period, program, speaker), method: :delete, data: { confirm: "잘못 누른게 아니라면 삭제합니다."}, class: "btn btn-danger") do %>
										<span class="fcw fwn glyphicon glyphicon-remove fs10"></span>
									<% end %>
								</div>
							<% end %>
							<%= link_to(new_admin_event_period_program_speaker_path(@event, period, program), class: "btn btn-success btn-xs mb5") do %>
								<span class="fcw fwn glyphicon glyphicon-plus fs10"></span>
							<% end %>
						</div>
					</td>
					<% end %>
				<% end %>	
			</tr>
		<% end %>
			<tr class="new_period">
				<td colspan="<%= @event.rooms.count+1 %>">
					<%= link_to new_admin_event_period_path(@event), :class => "btn btn-success" do %>
						<span class="glyphicon glyphicon-plus"></span> 새 시간대 추가하기
					<% end %>						
				</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/admin/events/_supporter.html.erb
<div class="supporters_section section">
	<h3>스폰서</h3>
	<% if @supporters.blank? %>
		<div class="new_supporter w100p tac">
			<p>스폰서가 한군데도 없습니다.</p>
			<%= link_to new_admin_event_supporter_path(@event) do %>
				<div class="btn btn-success">
					<span class="fcw fwn glyphicon glyphicon-plus fs10"></span> 스폰서 추가
				</div> 
			<% end %>
		</div>
	<% else %>
		<ul class="supporters">
			<% @supporters.each do |supporter| %>
				<li class="supporter">
					<%= link_to edit_admin_event_supporter_path(@event, supporter) do %>
						<div class="photo"><%= image_tag(supporter.photo.url(:camp5th)) if supporter.photo.present? %></div>
					<% end %>
					<% if supporter.link.present? %>
						<%= link_to "#{supporter.name}", supporter.link, target: "_blank" %>
					<% else %>
						<%= supporter.name %>
					<% end %>
				</li>
			<% end %>
			<li class="new_supporter">
				<%= link_to new_admin_event_supporter_path(@event) do %>
					<div class="new_photo btn btn-success">+</div>
					스폰서 추가 
				<% end %>
			</li>
		</ul>
	<% end %>
</div>

app/views/admin/events/edit.html.erb
<h1>행사 수정</h1>

<%= render 'form' %>

app/views/admin/events/index.html.erb
<div class="w100p">
	<% if notice.present? %>
		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<h1 class="dib">총 <%= content_tag :span, Event.count, :class => "font-important" %>건의 행사</h1>
	<%= link_to new_admin_event_path, :class => "btn btn-success fr mt15" do %>
		<span class="glyphicon glyphicon-plus"></span> 새 행사 시작하기
	<% end %>
	<hr class="mt10">
</div>

<% if @events.blank? %>
<div class="w100p tac">행사가 하나도 없습니다.</div>
<% end %>
<ul class="events">
  <% @events.each do |event| %>
		<li class="event tac">
			<%= link_to admin_event_path(event) do %>
			<div class="poster_wrapper">
				<%= image_tag(event.poster.url(:w240)) %>
			</div>
			<h4><%= event.title %></h4>
			<%= hdate(event.starts_at, "/") %> ~ <%= hdate(event.ends_at, "/") %><br>
			조회수 : <%= event.view_count %><br>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/admin/events/new.html.erb
<h1>새 행사 시작하기</h1>

<%= render 'form' %>

app/views/admin/events/show.html.erb
<% if notice.present? %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>

<ul class="breadcrumb">
  <li><%= link_to "행사 목록", admin_events_path %></li>
  <li class="active"><%= @event.title %></li>
</ul>


<div class="event_show">
	<%= render 'information' %>
	<%= render 'program' %>
	<%= render 'organizer' %>
	<hr>
	<%= render 'supporter' %>
</div>