config/routes.rb
Rails.application.routes.draw do
  root :to => "events#show", id: 5

  get "1" => "events#show", id: 1
  get "2" => "events#show", id: 2
  get "3" => "events#show", id: 3
  get "4" => "events#show", id: 4
  get "5" => "events#show", id: 5
  get "uxeye" => "events#show", id: 4
  get "history" => "histories#index"
  get "history/1" => "histories#show", id: 1
  get "history/2" => "histories#show", id: 2
  get "history/3" => "histories#show", id: 3
  get "history/4" => "histories#show", id: 4

  namespace :admin do
    root :to => "events#index"
    get "/" => "events#index"

    get "logout" => "sessions#destroy", as: "logout"
    get "login" => "sessions#new", as: "login"
    post "login" => "sessions#create"

    get 'stat' => "stats#index", :as => "stat"
    get 'stat_query' => "stats#query", :as => "stat_query"

    match "oauth/callback" => "oauth#callback", :via => :all
    match "oauth/:provider" => "oauth#oauth", :as => :auth_at_provider, :via => :all

    resources :events do
      resources :rooms
      resources :periods do
        resources :programs do
          resources :speakers
        end
      end
      resources :organizer_groups do
        resources :organizers
      end
      resources :organizers
      resources :supporters
    end
    resources :users
  end
end

app/models/program.rb
# == Schema Information
#
# Table name: programs
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  room_id    :string(255)
#  content    :text
#  position   :integer
#  period_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Program < ActiveRecord::Base
  belongs_to :period
  belongs_to :room  
  has_many :speakers, :dependent => :destroy
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < ApplicationController
	before_filter :require_organizer
	layout 'admin'
	
  def new
    @program = Program.new
  end
  def create
    p params
    params[:program][:period_id] = params[:period_id]
    @program = Program.new(program_params)
    if @program.save
      redirect_to admin_event_path(params[:event_id]), notice: '프로그램이 잘 생성되었습니다.'
    else
			p @program.errors
      render action: 'new'
    end
  end

  def edit
    @program = Program.find(params[:id])
  end
  def update
    p params
    @program = Program.find(params[:id])
    if @program.update(program_params)
      redirect_to admin_event_path(params[:event_id]), notice: '프로그램이 잘 수정되었습니다.'
    else
			p @program.errors
      render action: 'edit'
    end
  end

  def destroy
    @program = Program.find(params[:id])
    @program.destroy
		redirect_to admin_event_path(params[:event_id]), notice: '프로그램을 삭제했습니다.'
  end

  private
    def program_params
      params.require(:program).permit(:title, :position, :room_id, :content, :period_id)
    end
end

app/views/admin/programs/_form.html.erb
<% url = params[:action] == "new" ? admin_event_period_programs_path : admin_event_period_program_path %>

<div class="w300">
	<%= simple_form_for [:admin, @program], url: url do |f| %>
		<% @errors = @program.errors.messages %>

		<%= f.input :title, label: "프로그램 제목", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:title) %>
		<br>
		<%= f.input :room_id, collection: Event.find(params[:event_id]).rooms, label: "장소(방)", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:room) %>
		<br>
		<%= f.input :content, label: "내용 설명", label_html: { class: "fwb" }, input_html: { class: "form-control" }, error: false %>
		<% flash_error_message(:content) %>
		<br>
		<%= f.input :position, label: "정렬 순서", label_html: { class: "fwb" }, input_html: { class: "w75 form-control" }, error: false %>
		<% flash_error_message(:position) %>
		<hr>
		<%= render "/admin/events/form_confirm_or_cancel" %>
	<% end %>
</div>

app/views/admin/programs/edit.html.erb
<h1>프로그램 수정</h1>

<%= render 'form' %>

app/views/admin/programs/new.html.erb
<h1>새 프로그램 추가</h1>

<%= render 'form' %>