config/routes.rb
Rails.application.routes.draw do
  root :to => "events#show", id: 5

  get "1" => "events#show", id: 1
  get "2" => "events#show", id: 2
  get "3" => "events#show", id: 3
  get "4" => "events#show", id: 4
  get "5" => "events#show", id: 5
  get "uxeye" => "events#show", id: 4
  get "history" => "histories#index"
  get "history/1" => "histories#show", id: 1
  get "history/2" => "histories#show", id: 2
  get "history/3" => "histories#show", id: 3
  get "history/4" => "histories#show", id: 4

  namespace :admin do
    root :to => "events#index"
    get "/" => "events#index"

    get "logout" => "sessions#destroy", as: "logout"
    get "login" => "sessions#new", as: "login"
    post "login" => "sessions#create"

    get 'stat' => "stats#index", :as => "stat"
    get 'stat_query' => "stats#query", :as => "stat_query"

    match "oauth/callback" => "oauth#callback", :via => :all
    match "oauth/:provider" => "oauth#oauth", :as => :auth_at_provider, :via => :all

    resources :events do
      resources :rooms
      resources :periods do
        resources :programs do
          resources :speakers
        end
      end
      resources :organizer_groups do
        resources :organizers
      end
      resources :organizers
      resources :supporters
    end
    resources :users
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
	<meta charset="utf-8" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>UXCampSeoul</title>
	<%= render '/shared/meta' %>
	<%= stylesheet_link_tag		 "admin", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= javascript_include_tag "css3-mediaqueries" %>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
	   <script>
	      document.createElement('header');
	      document.createElement('nav');
	      document.createElement('section');
	      document.createElement('article');
	      document.createElement('aside');
	      document.createElement('footer');
	   </script>
	<![endif]-->
</head>
<!--[if lt IE 7]><body class="ie ie6"><![endif]-->
<!--[if IE 7]>	 <body class="ie ie7"><![endif]-->
<!--[if IE 8]>	 <body class="ie ie8"><![endif]-->
<!--[if gt IE 8]><!--><body><!--<![endif]-->

<div class="container">
	<div id="h"%>
		<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
			<div class="container">
		    <div class="navbar-header">
		      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
					<%= link_to "UXCS", "/", :class => "navbar-brand" %>
		    </div>
		    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
					<% if current_user.admin? %>
						<%= navigation_tag :class => "nav navbar-nav" do |m| %>
							<%= m.item "행사 관리", admin_events_path, :current => params[:controller] == "admin/events" %>
							<%= m.item "권한 관리", admin_users_path, :current => params[:controller] == "admin/users" %>
							<%= m.item "통계", admin_stat_path, :current => params[:controller] == "admin/stat" %>
						<% end %>
					<% else %>
						<%= navigation_tag :class => "nav navbar-nav" do |m| %>
							<%= m.item "행사 관리", admin_events_path, :current => params[:controller] == "admin/events" %>
							<%= m.item "통계", admin_stat_path, :current => params[:controller] == "admin/stat" %>
						<% end %>
					<% end %>
		      <ul class="nav navbar-nav navbar-right">
		        <li><%= link_to "#{current_user.name} (#{User::ROLES.index(current_user.role)})", edit_admin_user_path(current_user) %></li>
						<li class="last">
							<a href="<%= admin_logout_path %>"><i class="icon-off"></i> 로그아웃</a>
						</li>
		      </ul>
				</nav>
			</div>
		</header>
	</div>

	<div id="c" class="clearfix">
		<%= yield %>
	</div>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
  <title>UxcampSeoul</title>
	<%= render '/shared/meta' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "css3-mediaqueries" %>
  <%= csrf_meta_tags %>
	<!--[if lt IE 9]>
	   <script>
	      document.createElement('header');
	      document.createElement('nav');
	      document.createElement('section');
	      document.createElement('article');
	      document.createElement('aside');
	      document.createElement('footer');
	   </script>
	<![endif]-->
</head>
<body>

<%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-48136873-1', 'uxcamp.co.kr');
  ga('send', 'pageview');
</script>
</body>
</html>

app/views/layouts/camp5th.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
	<meta charset="utf-8" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<%= render '/shared/meta' %>
	<%= stylesheet_link_tag		 "camp5th", :media => "all" %>
	<%= javascript_include_tag "css3-mediaqueries" %>
	<%= csrf_meta_tags %>
</head>
<!--[if lt IE 7]><body class="ie ie6"><![endif]-->
<!--[if IE 7]>	 <body class="ie ie7"><![endif]-->
<!--[if IE 8]>	 <body class="ie ie8"><![endif]-->
<!--[if gt IE 8]><!--><body><!--<![endif]-->

<%= yield %>

<%= javascript_include_tag "camp5th" %>
<%= javascript_include_tag "jquery.scrollTo.min" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-48136873-1', 'uxcamp.co.kr');
  ga('send', 'pageview');
</script>
</body>
</html>

app/views/layouts/history.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
	<meta charset="utf-8" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>UXCampSeoul</title>
	<%= render '/shared/meta' %>
	<%= stylesheet_link_tag		 "history", :media => "all" %>
	<%= javascript_include_tag "css3-mediaqueries" %>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
	   <script>
	      document.createElement('header');
	      document.createElement('nav');
	      document.createElement('section');
	      document.createElement('article');
	      document.createElement('aside');
	      document.createElement('footer');
	   </script>
	<![endif]-->
</head>
<!--[if lt IE 7]><body class="ie ie6"><![endif]-->
<!--[if IE 7]>	 <body class="ie ie7"><![endif]-->
<!--[if IE 8]>	 <body class="ie ie8"><![endif]-->
<!--[if gt IE 8]><!--><body class="<%= params[:action] %>"><!--<![endif]-->

<div id="header" class="<%= params[:action] %>">
	<div class="centering">
		<div class="logo"><a class="uxcamp" href="/">
			<%= image_tag "/images/uxcamp5th/uxcamp_logo.jpg", class: "big logo", alt: "UX CampSeoul Logo" %>
			<%= image_tag (params[:action] == "index" ? "camp5th/uxcamp_logo.png" : "history/uxcamp_logo.png") %>
			<h1>UXCampSeoul</h1></a></div>
		<ul class="gnb">
			<li><a class="uxcamp" href="/">UX Camp Seoul 2014</a></li>
			<li><a class="history" href="/history">지난 행사</a></li>
		</ul>		
	</div>
</div>

<%= yield %>

<%= render 'shared/footer' %>

<%= javascript_include_tag "history" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-48136873-1', 'uxcamp.co.kr');
  ga('send', 'pageview');
</script>
</body>
</html>